### ISSUE TITLE
Does not install in Visual Studio 2022 Community Edition

### ISSUE THREAD

**Issue by James103** [ElektroStudios/Automatic-Temp-File-Cleaner-for-Visual-Studio#1]
The extension does not install in VS2022 Community Edition (which is the only edition I have). The install requirements on the README say "Visual Studio 2019 Community Edition or higher", which my VS2022 edition should meet. Can you please update the extension so it also works in VS2022?

<details>

<summary> Log of install failure </summary>

```
3/7/2023 3:41:56 AM - Microsoft VSIX Installer
3/7/2023 3:41:56 AM - -------------------------------------------
3/7/2023 3:41:56 AM - vsixinstaller.exe version:
3/7/2023 3:41:56 AM - 17.1.1035-preview2
3/7/2023 3:41:56 AM - -------------------------------------------
3/7/2023 3:41:56 AM - Command line parameters:
3/7/2023 3:41:56 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,[path to extension file's directory]\VsAutomaticTempFileCleaner.vsix
3/7/2023 3:41:56 AM - -------------------------------------------
3/7/2023 3:41:56 AM - Microsoft VSIX Installer
3/7/2023 3:41:56 AM - -------------------------------------------
3/7/2023 3:41:56 AM - Initializing Install...
3/7/2023 3:41:56 AM - Extension Details...
3/7/2023 3:41:56 AM - 	Identifier         : VsAutomaticTempFileCleaner.2dd5d924-3077-4867-860d-3f1319b97024
3/7/2023 3:41:56 AM - 	Name               : VsAutomaticTempFileCleaner
3/7/2023 3:41:56 AM - 	Author             : ElektroStudios
3/7/2023 3:41:56 AM - 	Version            : 1.0
3/7/2023 3:41:56 AM - 	Description        : Automatically cleans temporary files generated by Visual Studio when closing the IDE.
3/7/2023 3:41:56 AM - 	Locale             : en-US
3/7/2023 3:41:56 AM - 	MoreInfoURL        : 
3/7/2023 3:41:56 AM - 	InstalledByMSI     : False
3/7/2023 3:41:56 AM - 	SupportedFrameworkVersionRange : [4.5,)
3/7/2023 3:41:56 AM - 
3/7/2023 3:41:56 AM - 	SignatureState     : Unsigned
3/7/2023 3:41:56 AM - 	Supported Products : 
3/7/2023 3:41:56 AM - 		Microsoft.VisualStudio.Community
3/7/2023 3:41:56 AM - 			Version : [16.0,17.0)
3/7/2023 3:41:56 AM - 			ProductArchitecture : x86
3/7/2023 3:41:56 AM - 
3/7/2023 3:41:56 AM - 	References         : 
3/7/2023 3:41:56 AM - 		-------------------------------------------------------
3/7/2023 3:41:56 AM - 		Identifier   : Microsoft.VisualStudio.MPF.16.0
3/7/2023 3:41:56 AM - 		Name         : Visual Studio MPF 16.0
3/7/2023 3:41:56 AM - 		Version      : [16.0,17.0)
3/7/2023 3:41:56 AM - 		MoreInfoURL  : 
3/7/2023 3:41:56 AM - 		Nested       : No
3/7/2023 3:41:56 AM - 
3/7/2023 3:41:56 AM - 	Prerequisites      : 
3/7/2023 3:41:56 AM - 		-------------------------------------------------------
3/7/2023 3:41:56 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/7/2023 3:41:56 AM - 		Name         : Visual Studio core editor
3/7/2023 3:41:56 AM - 		Version      : [16.0,17.0)
3/7/2023 3:41:56 AM - 
3/7/2023 3:41:56 AM - Signature Details...
3/7/2023 3:41:56 AM - 	Extension is not signed.
3/7/2023 3:41:56 AM - 
3/7/2023 3:41:56 AM - Searching for applicable products...
3/7/2023 3:41:56 AM - Found installed product - Global Location
3/7/2023 3:41:56 AM - Found installed product - Visual Studio Community 2022
3/7/2023 3:41:56 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
</details>

**Comment by ElektroStudios** [comment]
Hi. I'm very sorry for the long delay, but I was not pending of issues for a long time.

The phrase of the README it referred to the lowest edition (Community) and higher editions (Professional, Enterprise) of Visual Studio 2019.

Please download the latest extension package by clicking [here](https://github.com/ElektroStudios/Automatic-Temp-File-Cleaner-for-Visual-Studio/releases/latest), which is ready to install for Visual Studio 2022 Community and higher editions.

If you still have any questions, feel free to continue this conversation (I'll be attentive).

I hope this helps you.

Thanks for your contribution!.
